# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  # Ubuntu  14.04.2
  #config.vm.box = 	"ubuntu/trusty64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false
 
  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # Ubuntu  14.04.2	
	
	config.vm.define "liferay", primary: true do |liferay|
		# Set to true in order to dowloand boxes while on the
		# BAH Network as the BAH's proxy server messes with the repo's SSL cert
		liferay.vm.box_download_insecure = true
		liferay.vm.box = "ubuntu/trusty64"
		liferay.vm.provider "virtualbox" do |vb|
			# Customize the amount of memory on the VM:
			vb.memory = "4096"
		end
		liferay.vm.network "private_network", ip: "192.168.33.20"
		liferay.vm.hostname = "liferay-server.local"
		liferay.vm.synced_folder "../ode-common", "/ode-common"
		liferay.vm.provision "shell", path: "../ode-common/disable_firewall_ufw.sh"
		liferay.vm.provision "shell", path: "./install_liferay.sh"
		liferay.vm.provision "shell", path: "../ode-common/install_spark.sh"
		liferay.vm.provision "shell", path: "./set_java_home.sh"
		liferay.vm.provision "shell", path: "../ode-common/update_host_file.sh"
	end
	config.vm.post_up_message = "Liferay server: http://192.168.33.20 \nDefaults:\nUserName: user@liferay.com\nPassword: test"
	
end
