/*******************************************************************************
 * Copyright (c) 2015 US DOT - Joint Program Office
 *
 * The Government has unlimited rights to all documents/material produced under 
 * this task order. All documents and materials, to include the source code of 
 * any software produced under this contract, shall be Government owned and the 
 * property of the Government with all rights and privileges of ownership/copyright 
 * belonging exclusively to the Government. These documents and materials may 
 * not be used or sold by the Contractor without written permission from the CO.
 * All materials supplied to the Government shall be the sole property of the 
 * Government and may not be used for any other purpose. This right does not 
 * abrogate any other Government rights.
 *
 * Contributors:
 *     Booz | Allen | Hamilton - initial API and implementation
 *******************************************************************************/
/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.7.4, Date: 23-Dec-2014.
 */
package com.bah.ode.util;

import java.io.BufferedOutputStream;
import java.io.FileOutputStream;
import java.io.PrintStream;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.logging.FileHandler;
import java.util.logging.Logger;
import java.util.logging.SimpleFormatter;

import com.bah.ode.asn.oss.semi.VehSitDataMessage;
import com.bah.ode.asn.oss.Oss;
import com.oss.asn1.Coder;
import com.oss.asn1printer.DataPrinter;

public class OssReaderWriter {

	private static Logger logger = Logger.getLogger(OssReaderWriter.class.getName());

	public static void main(String args[]) {
		String filename = new String("message.dat");
		boolean trace = false;
		boolean buffering = true;
		// Process command line arguments
		if (args.length > 0) {
			for (int i = 0; i < args.length; i++) {
				if (args[i].equals("-i"))
					filename = new String(args[++i]);
				else if (args[i].equals("-trace"))
					trace = true;
				else if (args[i].equals("-nobuffering"))
					buffering = false;
				else {
					System.out.println("usage: Reader [ -i <filename>");
					System.out.println("   -i <filename>  ");
					System.out.println("   -nobuffering disable I/O buffering");
					System.out.println("   -trace display trace info");
					System.exit(1);
				}
			}
		}

		Coder coder = Oss.getBERCoder();
		try {
			FileHandler handler = new FileHandler(filename + ".log", true);
			SimpleFormatter formatter = new SimpleFormatter();
			handler.setFormatter(formatter);
			logger.addHandler(handler);

			// // Create an input file stream object
			java.io.InputStream ins = buffering ?
			    new java.io.BufferedInputStream(
              			new java.io.FileInputStream(filename)) :
          				new java.io.FileInputStream(filename);

			logger.info("\n*** BER DECODING BEGIN ***\n");
			long decodeTime = System.currentTimeMillis();
			ArrayList<VehSitDataMessage> values = new ArrayList<VehSitDataMessage>();
			PrintWriter printOut = new PrintWriter(new PrintStream(filename + ".print"));
			DataPrinter printer = new DataPrinter();
			do {
				try {
					VehSitDataMessage value = (VehSitDataMessage) coder.decode(ins, new VehSitDataMessage());
					values.add(value);
					
					if (trace) {
						printer.print(value, printOut);
					}
				} catch (Exception e) {
					System.out.println("Decode complete.\n" + e.getMessage());
					break;
				}
			} while (true);
			ins.close();
			decodeTime = System.currentTimeMillis() - decodeTime;
			
			logger.info("Number of PDUs: " + values.size());
			logger.info("Decode Time: " + decodeTime + " ms");
			logger.info("Decode Rate: " + (int)((double)(values.size()) / ((double)decodeTime/1000)) + " PDUs/sec");

			logger.info("\n*** BER ENCODING BEGIN ***\n");
			java.io.OutputStream berOut = buffering ? 
			    new BufferedOutputStream(new FileOutputStream(filename + ".ber")) :
			    new FileOutputStream(filename + ".ber");
			long encodeTime = System.currentTimeMillis();
			for (VehSitDataMessage value: values) {
				try {
					coder.encode(value, berOut);
				} catch (Exception e) {
					System.out.println("Decode complete.\n" + e.getMessage());
					break;
				}
			}
			berOut.close();
			encodeTime = System.currentTimeMillis() - encodeTime;
			
			logger.info("Encode Time: " + encodeTime + " ms");
			logger.info("Encode Rate: " + (int)((double)(values.size()) / ((double)encodeTime/1000)) + " PDUs/sec");

		} catch (Exception e) {
			System.out.println(e.getMessage());
			e.printStackTrace();
			System.exit(1);
		} finally {
		}
	}
}
