# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ODE_v2.ui'
#
# Created: Tue Mar 15 14:37:08 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(642, 689)
        self.eadCase4Count = QtGui.QTabWidget(Dialog)
        self.eadCase4Count.setEnabled(True)
        self.eadCase4Count.setGeometry(QtCore.QRect(0, 150, 1201, 541))
        self.eadCase4Count.setMinimumSize(QtCore.QSize(600, 0))
        self.eadCase4Count.setObjectName("eadCase4Count")
        self.infloTab = QtGui.QWidget()
        self.infloTab.setObjectName("infloTab")
        self.label4 = QtGui.QLabel(self.infloTab)
        self.label4.setGeometry(QtCore.QRect(20, 10, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.label4.setFont(font)
        self.label4.setObjectName("label4")
        self.label5 = QtGui.QLabel(self.infloTab)
        self.label5.setGeometry(QtCore.QRect(20, 50, 101, 16))
        self.label5.setObjectName("label5")
        self.label6 = QtGui.QLabel(self.infloTab)
        self.label6.setGeometry(QtCore.QRect(20, 90, 151, 16))
        self.label6.setObjectName("label6")
        self.stLength = QtGui.QLineEdit(self.infloTab)
        self.stLength.setGeometry(QtCore.QRect(170, 90, 141, 22))
        self.stLength.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.stLength.setObjectName("stLength")
        self.label7 = QtGui.QLabel(self.infloTab)
        self.label7.setGeometry(QtCore.QRect(20, 130, 141, 16))
        self.label7.setObjectName("label7")
        self.sublinkLength = QtGui.QLineEdit(self.infloTab)
        self.sublinkLength.setGeometry(QtCore.QRect(170, 130, 141, 22))
        self.sublinkLength.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sublinkLength.setObjectName("sublinkLength")
        self.label8 = QtGui.QLabel(self.infloTab)
        self.label8.setGeometry(QtCore.QRect(20, 170, 151, 16))
        self.label8.setObjectName("label8")
        self.minSpeed = QtGui.QLineEdit(self.infloTab)
        self.minSpeed.setGeometry(QtCore.QRect(170, 170, 141, 22))
        self.minSpeed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.minSpeed.setObjectName("minSpeed")
        self.label9 = QtGui.QLabel(self.infloTab)
        self.label9.setGeometry(QtCore.QRect(20, 210, 151, 16))
        self.label9.setObjectName("label9")
        self.maxSpeed = QtGui.QLineEdit(self.infloTab)
        self.maxSpeed.setGeometry(QtCore.QRect(170, 210, 141, 22))
        self.maxSpeed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.maxSpeed.setObjectName("maxSpeed")
        self.label11 = QtGui.QLabel(self.infloTab)
        self.label11.setGeometry(QtCore.QRect(330, 90, 151, 16))
        self.label11.setObjectName("label11")
        self.dataType = QtGui.QLineEdit(self.infloTab)
        self.dataType.setGeometry(QtCore.QRect(420, 90, 111, 22))
        self.dataType.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dataType.setObjectName("dataType")
        self.startInflo = QtGui.QPushButton(self.infloTab)
        self.startInflo.setGeometry(QtCore.QRect(400, 150, 131, 28))
        self.startInflo.setObjectName("startInflo")
        self.label = QtGui.QLabel(self.infloTab)
        self.label.setGeometry(QtCore.QRect(470, 490, 141, 16))
        self.label.setObjectName("label")
        self.exitInflo = QtGui.QPushButton(self.infloTab)
        self.exitInflo.setGeometry(QtCore.QRect(400, 190, 131, 28))
        self.exitInflo.setObjectName("exitInflo")
        self.INFLOCorridor = QtGui.QComboBox(self.infloTab)
        self.INFLOCorridor.setGeometry(QtCore.QRect(170, 50, 361, 22))
        self.INFLOCorridor.setObjectName("INFLOCorridor")
        self.INFLOCorridor.addItem("")
        self.INFLOCorridor.addItem("")
        self.infloMessages = QtGui.QLabel(self.infloTab)
        self.infloMessages.setGeometry(QtCore.QRect(140, 260, 91, 16))
        self.infloMessages.setObjectName("infloMessages")
        self.infloMessagesCount = QtGui.QLabel(self.infloTab)
        self.infloMessagesCount.setGeometry(QtCore.QRect(230, 260, 51, 16))
        self.infloMessagesCount.setObjectName("infloMessagesCount")
        self.label_5 = QtGui.QLabel(self.infloTab)
        self.label_5.setGeometry(QtCore.QRect(370, 260, 81, 16))
        self.label_5.setObjectName("label_5")
        self.infloTriggersCount = QtGui.QLabel(self.infloTab)
        self.infloTriggersCount.setGeometry(QtCore.QRect(460, 260, 61, 16))
        self.infloTriggersCount.setObjectName("infloTriggersCount")
        self.infloPlot = QtGui.QWidget(self.infloTab)
        self.infloPlot.setGeometry(QtCore.QRect(39, 289, 511, 211))
        self.infloPlot.setObjectName("infloPlot")
        self.eadCase4Count.addTab(self.infloTab, "")
        self.inczoneTab = QtGui.QWidget()
        self.inczoneTab.setObjectName("inczoneTab")
        self.incClosedLanes = QtGui.QLineEdit(self.inczoneTab)
        self.incClosedLanes.setGeometry(QtCore.QRect(170, 200, 141, 22))
        self.incClosedLanes.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.incClosedLanes.setObjectName("incClosedLanes")
        self.label19 = QtGui.QLabel(self.inczoneTab)
        self.label19.setGeometry(QtCore.QRect(20, 120, 151, 16))
        self.label19.setObjectName("label19")
        self.startInczone = QtGui.QPushButton(self.inczoneTab)
        self.startInczone.setGeometry(QtCore.QRect(400, 140, 131, 28))
        self.startInczone.setObjectName("startInczone")
        self.label13 = QtGui.QLabel(self.inczoneTab)
        self.label13.setGeometry(QtCore.QRect(20, 40, 101, 16))
        self.label13.setObjectName("label13")
        self.label17 = QtGui.QLabel(self.inczoneTab)
        self.label17.setGeometry(QtCore.QRect(20, 200, 151, 16))
        self.label17.setObjectName("label17")
        self.incEnd = QtGui.QLineEdit(self.inczoneTab)
        self.incEnd.setGeometry(QtCore.QRect(170, 120, 141, 22))
        self.incEnd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.incEnd.setObjectName("incEnd")
        self.label18 = QtGui.QLabel(self.inczoneTab)
        self.label18.setGeometry(QtCore.QRect(20, 80, 131, 16))
        self.label18.setObjectName("label18")
        self.label16 = QtGui.QLabel(self.inczoneTab)
        self.label16.setGeometry(QtCore.QRect(20, 160, 151, 16))
        self.label16.setObjectName("label16")
        self.incClosureLength = QtGui.QLineEdit(self.inczoneTab)
        self.incClosureLength.setGeometry(QtCore.QRect(170, 160, 141, 22))
        self.incClosureLength.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.incClosureLength.setObjectName("incClosureLength")
        self.incStart = QtGui.QLineEdit(self.inczoneTab)
        self.incStart.setGeometry(QtCore.QRect(170, 80, 141, 22))
        self.incStart.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.incStart.setObjectName("incStart")
        self.label12 = QtGui.QLabel(self.inczoneTab)
        self.label12.setGeometry(QtCore.QRect(20, 0, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.label12.setFont(font)
        self.label12.setObjectName("label12")
        self.label_2 = QtGui.QLabel(self.inczoneTab)
        self.label_2.setGeometry(QtCore.QRect(470, 490, 141, 16))
        self.label_2.setObjectName("label_2")
        self.exitInczone = QtGui.QPushButton(self.inczoneTab)
        self.exitInczone.setGeometry(QtCore.QRect(400, 180, 131, 28))
        self.exitInczone.setObjectName("exitInczone")
        self.INCZONECorridor = QtGui.QComboBox(self.inczoneTab)
        self.INCZONECorridor.setGeometry(QtCore.QRect(170, 40, 351, 22))
        self.INCZONECorridor.setObjectName("INCZONECorridor")
        self.INCZONECorridor.addItem("")
        self.INCZONECorridor.addItem("")
        self.INCZONECorridor.addItem("")
        self.inczoneMessagesLabel = QtGui.QLabel(self.inczoneTab)
        self.inczoneMessagesLabel.setGeometry(QtCore.QRect(60, 250, 81, 16))
        self.inczoneMessagesLabel.setObjectName("inczoneMessagesLabel")
        self.inczoneAdvisoriesLabel = QtGui.QLabel(self.inczoneTab)
        self.inczoneAdvisoriesLabel.setGeometry(QtCore.QRect(190, 250, 91, 16))
        self.inczoneAdvisoriesLabel.setObjectName("inczoneAdvisoriesLabel")
        self.inczoneAlertsLabel = QtGui.QLabel(self.inczoneTab)
        self.inczoneAlertsLabel.setGeometry(QtCore.QRect(320, 250, 81, 16))
        self.inczoneAlertsLabel.setObjectName("inczoneAlertsLabel")
        self.inczoneWarningLabel = QtGui.QLabel(self.inczoneTab)
        self.inczoneWarningLabel.setGeometry(QtCore.QRect(430, 250, 81, 16))
        self.inczoneWarningLabel.setObjectName("inczoneWarningLabel")
        self.inczoneMessagesCount = QtGui.QLabel(self.inczoneTab)
        self.inczoneMessagesCount.setGeometry(QtCore.QRect(150, 250, 31, 16))
        self.inczoneMessagesCount.setObjectName("inczoneMessagesCount")
        self.inczoneAdvisoriesCount = QtGui.QLabel(self.inczoneTab)
        self.inczoneAdvisoriesCount.setGeometry(QtCore.QRect(280, 250, 41, 16))
        self.inczoneAdvisoriesCount.setObjectName("inczoneAdvisoriesCount")
        self.inczoneAlertsCount = QtGui.QLabel(self.inczoneTab)
        self.inczoneAlertsCount.setGeometry(QtCore.QRect(390, 250, 31, 16))
        self.inczoneAlertsCount.setObjectName("inczoneAlertsCount")
        self.inczoneWarningsCount = QtGui.QLabel(self.inczoneTab)
        self.inczoneWarningsCount.setGeometry(QtCore.QRect(520, 250, 71, 16))
        self.inczoneWarningsCount.setObjectName("inczoneWarningsCount")
        self.inczonePlot = QtGui.QWidget(self.inczoneTab)
        self.inczonePlot.setGeometry(QtCore.QRect(20, 270, 551, 221))
        self.inczonePlot.setObjectName("inczonePlot")
        self.eadCase4Count.addTab(self.inczoneTab, "")
        self.eadTab = QtGui.QWidget()
        self.eadTab.setObjectName("eadTab")
        self.label_3 = QtGui.QLabel(self.eadTab)
        self.label_3.setGeometry(QtCore.QRect(470, 490, 141, 16))
        self.label_3.setObjectName("label_3")
        self.label13_2 = QtGui.QLabel(self.eadTab)
        self.label13_2.setGeometry(QtCore.QRect(20, 50, 121, 16))
        self.label13_2.setObjectName("label13_2")
        self.label17_2 = QtGui.QLabel(self.eadTab)
        self.label17_2.setGeometry(QtCore.QRect(20, 210, 151, 16))
        self.label17_2.setObjectName("label17_2")
        self.label18_2 = QtGui.QLabel(self.eadTab)
        self.label18_2.setGeometry(QtCore.QRect(20, 90, 131, 16))
        self.label18_2.setObjectName("label18_2")
        self.label12_2 = QtGui.QLabel(self.eadTab)
        self.label12_2.setGeometry(QtCore.QRect(20, 10, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.label12_2.setFont(font)
        self.label12_2.setObjectName("label12_2")
        self.label16_2 = QtGui.QLabel(self.eadTab)
        self.label16_2.setGeometry(QtCore.QRect(20, 170, 151, 16))
        self.label16_2.setObjectName("label16_2")
        self.intFreq = QtGui.QLineEdit(self.eadTab)
        self.intFreq.setGeometry(QtCore.QRect(190, 170, 141, 22))
        self.intFreq.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.intFreq.setObjectName("intFreq")
        self.label19_2 = QtGui.QLabel(self.eadTab)
        self.label19_2.setGeometry(QtCore.QRect(20, 130, 151, 16))
        self.label19_2.setObjectName("label19_2")
        self.decelMax = QtGui.QLineEdit(self.eadTab)
        self.decelMax.setGeometry(QtCore.QRect(190, 130, 141, 22))
        self.decelMax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.decelMax.setObjectName("decelMax")
        self.startEadapp = QtGui.QPushButton(self.eadTab)
        self.startEadapp.setGeometry(QtCore.QRect(410, 150, 131, 28))
        self.startEadapp.setObjectName("startEadapp")
        self.exitEadapp = QtGui.QPushButton(self.eadTab)
        self.exitEadapp.setGeometry(QtCore.QRect(410, 190, 131, 28))
        self.exitEadapp.setObjectName("exitEadapp")
        self.speedLimit = QtGui.QLineEdit(self.eadTab)
        self.speedLimit.setGeometry(QtCore.QRect(190, 90, 141, 22))
        self.speedLimit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.speedLimit.setObjectName("speedLimit")
        self.vehFreq = QtGui.QLineEdit(self.eadTab)
        self.vehFreq.setGeometry(QtCore.QRect(190, 210, 141, 22))
        self.vehFreq.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.vehFreq.setObjectName("vehFreq")
        self.comboBox = QtGui.QComboBox(self.eadTab)
        self.comboBox.setGeometry(QtCore.QRect(190, 50, 351, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.eadPlot = QtGui.QWidget(self.eadTab)
        self.eadPlot.setGeometry(QtCore.QRect(20, 270, 541, 221))
        self.eadPlot.setObjectName("eadPlot")
        self.eadMessagesLabel = QtGui.QLabel(self.eadTab)
        self.eadMessagesLabel.setGeometry(QtCore.QRect(180, 250, 81, 16))
        self.eadMessagesLabel.setObjectName("eadMessagesLabel")
        self.eadCase5Label = QtGui.QLabel(self.eadTab)
        self.eadCase5Label.setGeometry(QtCore.QRect(320, 250, 101, 16))
        self.eadCase5Label.setObjectName("eadCase5Label")
        self.eadMessagesCount = QtGui.QLabel(self.eadTab)
        self.eadMessagesCount.setGeometry(QtCore.QRect(270, 250, 21, 16))
        self.eadMessagesCount.setObjectName("eadMessagesCount")
        self.eadCase5Count = QtGui.QLabel(self.eadTab)
        self.eadCase5Count.setGeometry(QtCore.QRect(430, 250, 21, 16))
        self.eadCase5Count.setObjectName("eadCase5Count")
        self.eadCase4Count.addTab(self.eadTab, "")
        self.mawTab = QtGui.QWidget()
        self.mawTab.setObjectName("mawTab")
        self.label4_3 = QtGui.QLabel(self.mawTab)
        self.label4_3.setGeometry(QtCore.QRect(20, 10, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.label4_3.setFont(font)
        self.label4_3.setObjectName("label4_3")
        self.label_4 = QtGui.QLabel(self.mawTab)
        self.label_4.setGeometry(QtCore.QRect(470, 490, 141, 16))
        self.label_4.setObjectName("label_4")
        self.label13_3 = QtGui.QLabel(self.mawTab)
        self.label13_3.setGeometry(QtCore.QRect(20, 50, 121, 16))
        self.label13_3.setObjectName("label13_3")
        self.mawArea = QtGui.QComboBox(self.mawTab)
        self.mawArea.setGeometry(QtCore.QRect(200, 50, 171, 22))
        self.mawArea.setObjectName("mawArea")
        self.mawArea.addItem("")
        self.mawArea.addItem("")
        self.exitMawapp = QtGui.QPushButton(self.mawTab)
        self.exitMawapp.setGeometry(QtCore.QRect(410, 90, 131, 28))
        self.exitMawapp.setObjectName("exitMawapp")
        self.label18_3 = QtGui.QLabel(self.mawTab)
        self.label18_3.setGeometry(QtCore.QRect(20, 90, 181, 16))
        self.label18_3.setObjectName("label18_3")
        self.mawFreq = QtGui.QLineEdit(self.mawTab)
        self.mawFreq.setGeometry(QtCore.QRect(200, 90, 171, 22))
        self.mawFreq.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mawFreq.setObjectName("mawFreq")
        self.startMawapp = QtGui.QPushButton(self.mawTab)
        self.startMawapp.setGeometry(QtCore.QRect(410, 50, 131, 28))
        self.startMawapp.setObjectName("startMawapp")
        self.mawPlot = QtGui.QWidget(self.mawTab)
        self.mawPlot.setGeometry(QtCore.QRect(29, 169, 521, 311))
        self.mawPlot.setObjectName("mawPlot")
        self.mawMessagesLabel = QtGui.QLabel(self.mawTab)
        self.mawMessagesLabel.setGeometry(QtCore.QRect(130, 150, 81, 16))
        self.mawMessagesLabel.setObjectName("mawMessagesLabel")
        self.mawMessagesCount = QtGui.QLabel(self.mawTab)
        self.mawMessagesCount.setGeometry(QtCore.QRect(220, 150, 31, 16))
        self.mawMessagesCount.setObjectName("mawMessagesCount")
        self.mawAlertsLabel = QtGui.QLabel(self.mawTab)
        self.mawAlertsLabel.setGeometry(QtCore.QRect(370, 150, 61, 16))
        self.mawAlertsLabel.setObjectName("mawAlertsLabel")
        self.mawAlertsCount = QtGui.QLabel(self.mawTab)
        self.mawAlertsCount.setGeometry(QtCore.QRect(440, 150, 31, 16))
        self.mawAlertsCount.setObjectName("mawAlertsCount")
        self.eadCase4Count.addTab(self.mawTab, "")
        self.title = QtGui.QLabel(Dialog)
        self.title.setGeometry(QtCore.QRect(90, 10, 471, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.serverIP = QtGui.QLineEdit(Dialog)
        self.serverIP.setGeometry(QtCore.QRect(130, 60, 141, 22))
        self.serverIP.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.serverIP.setObjectName("serverIP")
        self.depositDataBox = QtGui.QCheckBox(Dialog)
        self.depositDataBox.setGeometry(QtCore.QRect(30, 90, 111, 20))
        self.depositDataBox.setCheckable(True)
        self.depositDataBox.setChecked(True)
        self.depositDataBox.setAutoExclusive(True)
        self.depositDataBox.setObjectName("depositDataBox")
        self.fieldDataBox = QtGui.QCheckBox(Dialog)
        self.fieldDataBox.setGeometry(QtCore.QRect(140, 90, 101, 20))
        self.fieldDataBox.setCheckable(True)
        self.fieldDataBox.setObjectName("fieldDataBox")
        self.label1_2 = QtGui.QLabel(Dialog)
        self.label1_2.setGeometry(QtCore.QRect(30, 60, 101, 16))
        self.label1_2.setObjectName("label1_2")
        self.label2 = QtGui.QLabel(Dialog)
        self.label2.setGeometry(QtCore.QRect(340, 60, 71, 16))
        self.label2.setObjectName("label2")
        self.label3 = QtGui.QLabel(Dialog)
        self.label3.setGeometry(QtCore.QRect(340, 90, 71, 16))
        self.label3.setObjectName("label3")
        self.username = QtGui.QLineEdit(Dialog)
        self.username.setGeometry(QtCore.QRect(410, 60, 151, 22))
        self.username.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.username.setObjectName("username")
        self.password = QtGui.QLineEdit(Dialog)
        self.password.setGeometry(QtCore.QRect(410, 90, 151, 22))
        self.password.setEchoMode(QtGui.QLineEdit.PasswordEchoOnEdit)
        self.password.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.password.setObjectName("password")
        self.fileUploadBox = QtGui.QCheckBox(Dialog)
        self.fileUploadBox.setGeometry(QtCore.QRect(230, 90, 101, 20))
        self.fileUploadBox.setCheckable(True)
        self.fileUploadBox.setObjectName("fileUploadBox")
        self.uploadFileText = QtGui.QLineEdit(Dialog)
        self.uploadFileText.setGeometry(QtCore.QRect(70, 120, 141, 20))
        self.uploadFileText.setObjectName("uploadFileText")
        self.uploadFileLabel = QtGui.QLabel(Dialog)
        self.uploadFileLabel.setGeometry(QtCore.QRect(30, 120, 71, 16))
        self.uploadFileLabel.setObjectName("uploadFileLabel")
        self.browseButton = QtGui.QPushButton(Dialog)
        self.browseButton.setGeometry(QtCore.QRect(220, 120, 81, 21))
        self.browseButton.setObjectName("browseButton")

        self.retranslateUi(Dialog)
        self.eadCase4Count.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label4.setText(QtGui.QApplication.translate("Dialog", "INFLO Speed Harmonization Settings:", None, QtGui.QApplication.UnicodeUTF8))
        self.label5.setText(QtGui.QApplication.translate("Dialog", "Corridor Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label6.setText(QtGui.QApplication.translate("Dialog", "Corridor Length (miles):", None, QtGui.QApplication.UnicodeUTF8))
        self.stLength.setText(QtGui.QApplication.translate("Dialog", "0.5", None, QtGui.QApplication.UnicodeUTF8))
        self.label7.setText(QtGui.QApplication.translate("Dialog", "Sublink Length (miles):", None, QtGui.QApplication.UnicodeUTF8))
        self.sublinkLength.setText(QtGui.QApplication.translate("Dialog", "0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.label8.setText(QtGui.QApplication.translate("Dialog", "Minimum Speed (mph):", None, QtGui.QApplication.UnicodeUTF8))
        self.minSpeed.setText(QtGui.QApplication.translate("Dialog", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.label9.setText(QtGui.QApplication.translate("Dialog", "Maximum Speed (mph):", None, QtGui.QApplication.UnicodeUTF8))
        self.maxSpeed.setText(QtGui.QApplication.translate("Dialog", "45", None, QtGui.QApplication.UnicodeUTF8))
        self.label11.setText(QtGui.QApplication.translate("Dialog", "Type(s) of Data:", None, QtGui.QApplication.UnicodeUTF8))
        self.dataType.setText(QtGui.QApplication.translate("Dialog", "CV", None, QtGui.QApplication.UnicodeUTF8))
        self.startInflo.setText(QtGui.QApplication.translate("Dialog", "Start Application", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Booz | Allen | Hamilton", None, QtGui.QApplication.UnicodeUTF8))
        self.exitInflo.setText(QtGui.QApplication.translate("Dialog", "Exit Application", None, QtGui.QApplication.UnicodeUTF8))
        self.INFLOCorridor.setItemText(0, QtGui.QApplication.translate("Dialog", "Larned St (Downtown)", None, QtGui.QApplication.UnicodeUTF8))
        self.INFLOCorridor.setItemText(1, QtGui.QApplication.translate("Dialog", "Telegraph Road", None, QtGui.QApplication.UnicodeUTF8))
        self.infloMessages.setText(QtGui.QApplication.translate("Dialog", "Total Messages:", None, QtGui.QApplication.UnicodeUTF8))
        self.infloMessagesCount.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Total Triggers:", None, QtGui.QApplication.UnicodeUTF8))
        self.infloTriggersCount.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.eadCase4Count.setTabText(self.eadCase4Count.indexOf(self.infloTab), QtGui.QApplication.translate("Dialog", "Speed Harmonization", None, QtGui.QApplication.UnicodeUTF8))
        self.incClosedLanes.setText(QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label19.setText(QtGui.QApplication.translate("Dialog", "Incident EndTime:", None, QtGui.QApplication.UnicodeUTF8))
        self.startInczone.setText(QtGui.QApplication.translate("Dialog", "Start Application", None, QtGui.QApplication.UnicodeUTF8))
        self.label13.setText(QtGui.QApplication.translate("Dialog", "Corridor Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label17.setText(QtGui.QApplication.translate("Dialog", "Lanes Closed:", None, QtGui.QApplication.UnicodeUTF8))
        self.incEnd.setText(QtGui.QApplication.translate("Dialog", "14:30", None, QtGui.QApplication.UnicodeUTF8))
        self.label18.setText(QtGui.QApplication.translate("Dialog", "Incident StartTime:", None, QtGui.QApplication.UnicodeUTF8))
        self.label16.setText(QtGui.QApplication.translate("Dialog", "Length of Closure (mile):", None, QtGui.QApplication.UnicodeUTF8))
        self.incClosureLength.setText(QtGui.QApplication.translate("Dialog", "0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.incStart.setText(QtGui.QApplication.translate("Dialog", "14:00", None, QtGui.QApplication.UnicodeUTF8))
        self.label12.setText(QtGui.QApplication.translate("Dialog", "INC-ZONE Application Settings:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Booz | Allen | Hamilton", None, QtGui.QApplication.UnicodeUTF8))
        self.exitInczone.setText(QtGui.QApplication.translate("Dialog", "Exit Application", None, QtGui.QApplication.UnicodeUTF8))
        self.INCZONECorridor.setItemText(0, QtGui.QApplication.translate("Dialog", "Congress St (Downtown)", None, QtGui.QApplication.UnicodeUTF8))
        self.INCZONECorridor.setItemText(1, QtGui.QApplication.translate("Dialog", "NB Telegraph Road", None, QtGui.QApplication.UnicodeUTF8))
        self.INCZONECorridor.setItemText(2, QtGui.QApplication.translate("Dialog", "SB Telegraph Road", None, QtGui.QApplication.UnicodeUTF8))
        self.inczoneMessagesLabel.setText(QtGui.QApplication.translate("Dialog", "Total Messages:", None, QtGui.QApplication.UnicodeUTF8))
        self.inczoneAdvisoriesLabel.setText(QtGui.QApplication.translate("Dialog", "Total Advisories:", None, QtGui.QApplication.UnicodeUTF8))
        self.inczoneAlertsLabel.setText(QtGui.QApplication.translate("Dialog", "Total Alerts:", None, QtGui.QApplication.UnicodeUTF8))
        self.inczoneWarningLabel.setText(QtGui.QApplication.translate("Dialog", "Total Warnings:", None, QtGui.QApplication.UnicodeUTF8))
        self.inczoneMessagesCount.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.inczoneAdvisoriesCount.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.inczoneAlertsCount.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.inczoneWarningsCount.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.eadCase4Count.setTabText(self.eadCase4Count.indexOf(self.inczoneTab), QtGui.QApplication.translate("Dialog", "Incident Zone Alerts", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Booz | Allen | Hamilton", None, QtGui.QApplication.UnicodeUTF8))
        self.label13_2.setText(QtGui.QApplication.translate("Dialog", "Intersection Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label17_2.setText(QtGui.QApplication.translate("Dialog", "Vehicle Data Freq (s):", None, QtGui.QApplication.UnicodeUTF8))
        self.label18_2.setText(QtGui.QApplication.translate("Dialog", "Roadway Speed Limit:", None, QtGui.QApplication.UnicodeUTF8))
        self.label12_2.setText(QtGui.QApplication.translate("Dialog", "Eco-Approach and Departure Application Settings:", None, QtGui.QApplication.UnicodeUTF8))
        self.label16_2.setText(QtGui.QApplication.translate("Dialog", "Intersection Data Freq (s):", None, QtGui.QApplication.UnicodeUTF8))
        self.intFreq.setText(QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label19_2.setText(QtGui.QApplication.translate("Dialog", "Allowable Deceleration:", None, QtGui.QApplication.UnicodeUTF8))
        self.decelMax.setText(QtGui.QApplication.translate("Dialog", "1.5", None, QtGui.QApplication.UnicodeUTF8))
        self.startEadapp.setText(QtGui.QApplication.translate("Dialog", "Start Application", None, QtGui.QApplication.UnicodeUTF8))
        self.exitEadapp.setText(QtGui.QApplication.translate("Dialog", "Exit Application", None, QtGui.QApplication.UnicodeUTF8))
        self.speedLimit.setText(QtGui.QApplication.translate("Dialog", "35", None, QtGui.QApplication.UnicodeUTF8))
        self.vehFreq.setText(QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("Dialog", "Washington St and Congress St", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("Dialog", "Woodward Ave and Congress St", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("Dialog", "SB Telegraph Rd and 10-mile Rd", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(3, QtGui.QApplication.translate("Dialog", "NB Telegraph Rd and 12-mile Rd", None, QtGui.QApplication.UnicodeUTF8))
        self.eadMessagesLabel.setText(QtGui.QApplication.translate("Dialog", "Total Messages:", None, QtGui.QApplication.UnicodeUTF8))
        self.eadCase5Label.setText(QtGui.QApplication.translate("Dialog", "Total Case 5 Alerts:", None, QtGui.QApplication.UnicodeUTF8))
        self.eadMessagesCount.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.eadCase5Count.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.eadCase4Count.setTabText(self.eadCase4Count.indexOf(self.eadTab), QtGui.QApplication.translate("Dialog", "Eco Approach Departure", None, QtGui.QApplication.UnicodeUTF8))
        self.label4_3.setText(QtGui.QApplication.translate("Dialog", "Motorists Advisory and Warnings Settings:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Booz | Allen | Hamilton", None, QtGui.QApplication.UnicodeUTF8))
        self.label13_3.setText(QtGui.QApplication.translate("Dialog", "Testbed Area:", None, QtGui.QApplication.UnicodeUTF8))
        self.mawArea.setItemText(0, QtGui.QApplication.translate("Dialog", "Downtown Network", None, QtGui.QApplication.UnicodeUTF8))
        self.mawArea.setItemText(1, QtGui.QApplication.translate("Dialog", "Telegraph Rd. Network", None, QtGui.QApplication.UnicodeUTF8))
        self.exitMawapp.setText(QtGui.QApplication.translate("Dialog", "Exit Application", None, QtGui.QApplication.UnicodeUTF8))
        self.label18_3.setText(QtGui.QApplication.translate("Dialog", "Advisory Update Frequency (s):", None, QtGui.QApplication.UnicodeUTF8))
        self.mawFreq.setText(QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.startMawapp.setText(QtGui.QApplication.translate("Dialog", "Start Application", None, QtGui.QApplication.UnicodeUTF8))
        self.mawMessagesLabel.setText(QtGui.QApplication.translate("Dialog", "Total Messages:", None, QtGui.QApplication.UnicodeUTF8))
        self.mawMessagesCount.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.mawAlertsLabel.setText(QtGui.QApplication.translate("Dialog", "Total Alerts:", None, QtGui.QApplication.UnicodeUTF8))
        self.mawAlertsCount.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.eadCase4Count.setTabText(self.eadCase4Count.indexOf(self.mawTab), QtGui.QApplication.translate("Dialog", "Road Weather Application", None, QtGui.QApplication.UnicodeUTF8))
        self.title.setText(QtGui.QApplication.translate("Dialog", "ODE Field Test Demonstration App", None, QtGui.QApplication.UnicodeUTF8))
        self.serverIP.setText(QtGui.QApplication.translate("Dialog", "52.90.45.32:8080/ode", None, QtGui.QApplication.UnicodeUTF8))
        self.depositDataBox.setText(QtGui.QApplication.translate("Dialog", "Deposit Data", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldDataBox.setText(QtGui.QApplication.translate("Dialog", "Field Data", None, QtGui.QApplication.UnicodeUTF8))
        self.label1_2.setText(QtGui.QApplication.translate("Dialog", "Server Address:", None, QtGui.QApplication.UnicodeUTF8))
        self.label2.setText(QtGui.QApplication.translate("Dialog", "Username:", None, QtGui.QApplication.UnicodeUTF8))
        self.label3.setText(QtGui.QApplication.translate("Dialog", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.username.setText(QtGui.QApplication.translate("Dialog", "sampleuser@liferay.com", None, QtGui.QApplication.UnicodeUTF8))
        self.password.setText(QtGui.QApplication.translate("Dialog", "ComplexPassword", None, QtGui.QApplication.UnicodeUTF8))
        self.fileUploadBox.setText(QtGui.QApplication.translate("Dialog", "File Upload", None, QtGui.QApplication.UnicodeUTF8))
        self.uploadFileLabel.setText(QtGui.QApplication.translate("Dialog", "File:", None, QtGui.QApplication.UnicodeUTF8))
        self.browseButton.setText(QtGui.QApplication.translate("Dialog", "Browse", None, QtGui.QApplication.UnicodeUTF8))

