# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  	# ambari box will start when no box is specified
    config.vm.define "ambari", primary: true do |ambari|
		# Set to true in order to dowloand boxes while on the
		# BAH Network as the BAH's proxy server messes with the repo's SSL cert
		ambari.vm.box_download_insecure = true
		ambari.vm.box = "chef/centos-6.5"
		ambari.vm.provider "virtualbox" do |vb|
			# Customize the amount of memory on the VM:
			vb.memory = "2048"
		end
		ambari.vm.network "private_network", ip: "192.168.33.10"
		ambari.vm.hostname = "ambari-server"
		ambari.vm.synced_folder "../ode-common", "/ode-common"
		ambari.vm.provision "shell", path: "./server_setup.sh"
		ambari.vm.provision "shell", path: "./install_ambari.sh"
		ambari.vm.provision "shell", path: "../ode-common/install_spark.sh"
		ambari.vm.provision "shell", path: "../ode-common/update_host_file.sh"
	end
	
	config.vm.define "hdp1", primary: false do |hdp1|
		# Set to true in order to dowloand boxes while on the
		# BAH Network as the BAH's proxy server messes with the repo's SSL cert
		hdp1.vm.box_download_insecure = true
		hdp1.vm.box = "chef/centos-6.5"
		hdp1.vm.provider "virtualbox" do |vb|
			# Customize the amount of memory on the VM:
			vb.memory = "2048"
		end
		hdp1.vm.network "private_network", ip: "192.168.33.11"
		hdp1.vm.hostname = "hdp1-server.local"
		hdp1.vm.synced_folder "../ode-common", "/ode-common"
		hdp1.vm.provision "shell", path: "./server_setup.sh"
		hdp1.vm.provision "shell", path: "./hadoop_node_setup.sh"
		hdp1.vm.provision "shell", path: "../ode-common/install_spark.sh"
		hdp1.vm.provision "shell", path: "../ode-common/update_host_file.sh"
	end
	
	config.vm.define "hdp2", primary: false do |hdp2|
		# Set to true in order to dowloand boxes while on the
		# BAH Network as the BAH's proxy server messes with the repo's SSL cert
		hdp2.vm.box_download_insecure = true
		hdp2.vm.box = "chef/centos-6.5"
		hdp2.vm.provider "virtualbox" do |vb|
			# Customize the amount of memory on the VM:
			vb.memory = "1024"
		end
		hdp2.vm.network "private_network", ip: "192.168.33.12"
		hdp2.vm.hostname = "hdp2-server.local"
		hdp2.vm.synced_folder "../ode-common", "/ode-common"
		hdp2.vm.provision "shell", path: "./server_setup.sh"
		hdp2.vm.provision "shell", path: "./hadoop_node_setup.sh"
		hdp2.vm.provision "shell", path: "../ode-common/install_spark.sh"
		hdp2.vm.provision "shell", path: "../ode-common/update_host_file.sh"
	end
		
	config.vm.post_up_message = "Amabari server: http://192.168.33.10:8080 \nUserName: admin \nPassword: admin"
	
end
