
SUCCESS = 'SUCCESS'
FAILURE ='FAILURE'
SOURCE_CONNECTION_ERROR = 'SOURCE_CONNECTION_ERROR'
INVALID_REQUEST_TYPE_ERROR = 'INVALID_REQUEST_TYPE_ERROR'
INVALID_DATA_TYPE_ERROR = 'INVALID_DATA_TYPE_ERROR'
 
def get_all_statuses():
	return [
		SUCCESS,
		FAILURE,
		SOURCE_CONNECTION_ERROR,
		INVALID_REQUEST_TYPE_ERROR,
		INVALID_DATA_TYPE_ERROR
	]